name: Clang-Tidy Linter

on:
  pull_request:
    paths:
      - '**.c'
      - '**.h'
      - '**.cpp'
      - '**.hpp'

jobs:
  lint:
    name: Run clang-tidy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.c
            **/*.h
            **/*.cpp
            **/*.hpp

      - name: Environment Setup and Compilation Database
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          sudo apt-get update -qq > /dev/null
          sudo apt-get install -y -qq clang-tidy bear > /dev/null
          echo "Environment Setup done!"
          bear -- make > /dev/null
          echo "Compilation db done!"

      - name: Execute clang-tidy
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          find src/ -name "*.cpp" -exec clang-tidy -p . --warnings-as-errors='*' {} +
